[functions]
  external_node_modules = ["express", "cors", "axios", "node-cache"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/fetchGames/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
