export { Logo } from './Logo'
export { PCIcon } from './PCIcon'
export { PlaystationIcon } from './PlaystationIcon'
export { XboxIcon } from './XboxIcon'
export { SwitchIcon } from './SwitchIcon'
export { RPGIcon } from './RPGIcon'
export { ShooterIcon } from './ShooterIcon'
export { StrategyIcon } from './StrategyIcon'
